spring:
    datasource:
             url: jdbc:h2:file:C:/Users/sunilkumar.havapnor/test/sample
             driverClassName: org.h2.Driver
             username: sa
             password: sa
             platform: org.hibernate.dialect.H2Dialect
    h2:
     console:
          enabled: true
          path: /h2
             
server:
   port : 5050
   
   